#This is where the script installing nxlog on ubuntu devices will go, huzzah!


- hosts: linux
  tasks:
    - name: Install NXLog (Linux)
      apt:
        name: nxlog
        state: present

    - name: Copy NXLog config (Linux)
      copy:
        src: nxlog.conf
        dest: /etc/nxlog/nxlog.conf   # Linux path

    - name: Start NXLog service (Linux)
      service:
        name: nxlog
        state: started
